---
apiVersion: v1
kind: Pod
namespace: 
metadata:
  name: rmf-building-map-server
spec:
  restartPolicy: Always
  hostNetwork: true
  containers:
    - name: rmf-building-map-server
      image: {{ .Values.builder_ns }}/rmf-site
      imagePullPolicy: Always
      env:
        - name: {{ .Values.global.DDS_ENV | quote }}
          value: {{ .Values.global.DDS_CONFIG | quote }}
        - name: ROS_DOMAIN_ID
          value: {{ .Values.global.ROS_DOMAIN_ID | quote }}
        - name: RMW_IMPLEMENTATION
          value: {{ .Values.global.RMW_IMPLEMENTATION | quote }}
        - name: RMF_BUILDING_MAP_SERVER_CONFIG_PATH
          value: {{ .Values.global.RMF_BUILDING_MAP_SERVER_CONFIG_PATH | quote }}
      command: ["/bin/bash"]
      args: 
        - -c
        - >
          /ros_entrypoint.sh
          ros2 run rmf_building_map_tools building_map_server
          $(RMF_BUILDING_MAP_SERVER_CONFIG_PATH)
      volumeMounts:
        - mountPath: {{ .Values.global.DDS_CONFIG_MOUNTPATH | quote }}
          name: {{ .Values.global.DDS_CONFIG_VOLUME | quote }}
  volumes:
    - name: {{ .Values.global.DDS_CONFIG_VOLUME | quote }}
      configMap:
        name: {{ .Values.global.DDS_CONFIG_VOLUME | quote }}

---
# Any site specific fleet adapters may be added here